using System.Text;
using CodeIntel.Server.Models;

namespace CodeIntel.Server.Services;

public interface IReportGenerator
{
    string GenerateMarkdown(AnalysisResult result, string? referenceFilename = null);
}

public class ReportGenerator : IReportGenerator
{
    public string GenerateMarkdown(AnalysisResult result, string? referenceFilename = null)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Code Intelligence Report");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {result.CompletedAt:yyyy-MM-dd HH:mm:ss} UTC  ");
        sb.AppendLine($"**Mode:** {DescribeMode(result)}  ");
        sb.AppendLine($"**Duration:** {result.Duration.TotalSeconds:F1}s  ");
        sb.AppendLine($"**Context tokens:** ~{result.ContextTokens:N0}");
        sb.AppendLine();

        sb.AppendLine("## Scope");
        sb.AppendLine();
        if (result.AnalyzedFiles.Count == 0)
        {
            sb.AppendLine("_(no files)_");
        }
        else
        {
            foreach (var file in result.AnalyzedFiles)
                sb.AppendLine($"- `{file}`");
        }
        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(result.FreeTextPrompt))
        {
            sb.AppendLine("## Question");
            sb.AppendLine();
            sb.AppendLine($"> {result.FreeTextPrompt.Replace("\n", "\n> ")}");
            sb.AppendLine();
        }

        sb.AppendLine("## Findings");
        sb.AppendLine();
        if (result.Findings.Count == 0)
        {
            sb.AppendLine("_No structured findings emitted. See raw output below._");
        }
        else
        {
            var bySeverity = result.Findings
                .GroupBy(f => f.Severity)
                .OrderBy(g => (int)g.Key);

            foreach (var group in bySeverity)
            {
                sb.AppendLine($"### {SeverityIcon(group.Key)} {group.Key} ({group.Count()})");
                sb.AppendLine();
                foreach (var finding in group)
                {
                    sb.AppendLine($"#### {finding.Title}");
                    if (!string.IsNullOrWhiteSpace(finding.FilePath))
                    {
                        var loc = finding.LineNumber.HasValue
                            ? $"`{finding.FilePath}:{finding.LineNumber.Value}`"
                            : $"`{finding.FilePath}`";
                        sb.AppendLine($"**Location:** {loc}");
                    }
                    sb.AppendLine();
                    sb.AppendLine(finding.Description);
                    if (!string.IsNullOrWhiteSpace(finding.CodeSnippet))
                    {
                        sb.AppendLine();
                        sb.AppendLine($"```{CodeLang(finding.FilePath)}");
                        sb.AppendLine(finding.CodeSnippet);
                        sb.AppendLine("```");
                    }
                    sb.AppendLine();
                }
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## Copilot Next Step");
        sb.AppendLine();
        var brief = BuildCopilotBrief(result);
        sb.AppendLine(brief.Lead);
        sb.AppendLine();
        if (!string.IsNullOrEmpty(referenceFilename))
        {
            sb.AppendLine("Reference this file in Copilot Chat:");
            sb.AppendLine();
            sb.AppendLine($"```text");
            sb.AppendLine($"#file:{referenceFilename}");
            sb.AppendLine("```");
            sb.AppendLine();
        }
        sb.AppendLine("Then ask:");
        sb.AppendLine();
        sb.AppendLine("```text");
        sb.AppendLine(brief.PromptBody);
        sb.AppendLine("```");
        sb.AppendLine();

        sb.AppendLine("<details>");
        sb.AppendLine("<summary>Raw LLM output</summary>");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine(result.RawLlmOutput);
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("</details>");

        return sb.ToString();
    }

    private record CopilotBrief(string Lead, string PromptBody);

    private static CopilotBrief BuildCopilotBrief(AnalysisResult result)
    {
        if (result.Mode == AnalysisMode.FreeText)
        {
            var question = string.IsNullOrWhiteSpace(result.FreeTextPrompt)
                ? "the original question above"
                : result.FreeTextPrompt!.Trim();
            return new(
                "Use the findings above as starting context to address the developer's question.",
                $"The findings above were generated by a local model investigating this question:\n\n  \"{question}\"\n\nUsing the findings as evidence, give the most accurate, complete answer you can. Cite specific file paths and line numbers from the findings. If a finding seems wrong, say so and explain why."
            );
        }

        return result.PresetKey switch
        {
            "find-bugs" => new(
                "The local model surfaced potential bugs. Use Copilot to verify, prioritize, and propose concrete fixes.",
                """
                Review each finding above. For every high-severity item:
                  1. Open the referenced file and confirm the bug actually exists.
                  2. If real, propose a precise code edit (show the diff).
                  3. Explain the failure mode and why the fix is correct.
                  4. Note any related code paths that should also be checked.

                If a finding is a false positive, say so and explain.
                Group your output by file. End with a one-line recommendation for next action.
                """),

            "find-dead-code" => new(
                "The local model flagged candidates for dead code. Verify each before deleting.",
                """
                For each candidate above:
                  1. Confirm there are truly no references — consider reflection, dependency injection,
                     test-only usage, public API surface, and dynamic dispatch.
                  2. If safe to remove, propose the exact edit (file, lines to delete).
                  3. If you cannot confirm, mark it as uncertain and explain what would prove safety.

                Group output by file. Recommend a deletion order if any items have dependencies on each other.
                """),

            "find-business-rules" => new(
                "The local model extracted business rules from the code. Use Copilot to refine them into documentation.",
                """
                For each rule above:
                  1. Restate it in plain business language (no code terminology).
                  2. Identify the source-of-truth code path (file:line).
                  3. Flag any rules that appear contradictory, redundant, or unenforced.
                  4. Note rules that lack obvious test coverage.

                Produce a flat numbered list grouped by domain area. End with open questions for product / domain owners.
                """),

            "summarize" => new(
                "The local model produced a synopsis of the code. Use Copilot to refine into a developer-facing overview.",
                """
                Using the synopsis above, produce a one-page architecture overview:
                  - What this code does (2-3 sentences).
                  - Key components and their responsibilities (bulleted).
                  - Important data flows or call paths.
                  - External dependencies (libraries, services, databases).
                  - Risks, surprises, or unclear areas a new dev should know about.

                Keep it dense and skimmable. Reference specific files when relevant.
                """),

            _ => new(
                "Use the findings above as input for follow-up analysis.",
                "Review the findings above. Verify their accuracy, prioritize them, and propose specific next actions. Reference file paths and line numbers from the findings in your response."),
        };
    }

    private static string CodeLang(string? filePath) =>
        Path.GetExtension(filePath)?.ToLowerInvariant() switch
        {
            ".cs" => "csharp",
            ".sql" or ".pkb" or ".pkg" or ".pks" or ".pls" => "sql",
            ".ts" or ".tsx" => "typescript",
            ".js" or ".jsx" => "javascript",
            ".py" => "python",
            ".go" => "go",
            ".java" => "java",
            _ => ""
        };

    private static string DescribeMode(AnalysisResult r) => r.Mode switch
    {
        AnalysisMode.Preset => $"Preset — {r.PresetKey}",
        AnalysisMode.FreeText => "Free-text question",
        _ => r.Mode.ToString()
    };

    private static string SeverityIcon(Severity s) => s switch
    {
        Severity.Bug => "🔴",
        Severity.Warning => "🟡",
        Severity.Suggestion => "🟢",
        Severity.DeadCode => "💀",
        Severity.Info => "🔵",
        _ => "•"
    };
}
